#!/bin/bash

### BEGIN INIT INFO
# Provides:          mykeystore
# Required-Start:    nginx
# Required-Stop:     nginx
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the mykeystore service
# Description:       starts mykeystore using start-stop-daemon
### END INIT INFO

NAME=keystore
USER=mykeystore
BIN=/usr/local/bin/$NAME
CONFIG=/usr/local/etc/mykeystore/config.json
PID=/run/mykeystore

. /lib/lsb/init-functions

#0 if daemon started
#1 if daemon was running
#2 if daemon could not be started
start_mykeystore () {
    if [ -z $(grep $USER /etc/passwd) ]
      then
        echo "User $USER not found."
        return 2
    fi
    start-stop-daemon -c $USER --start --quiet --make-pidfile --pidfile $PID \
      --background --exec $BIN --test > /dev/null || return 1
    start-stop-daemon -c $USER --start --quiet --make-pidfile --pidfile $PID \
      --background --exec $BIN -- --config $CONFIG 2>/dev/null || return 2
}

stop_mykeystore () {
  start-stop-daemon --stop --quiet --pidfile $PID --name $NAME
}

case "$1" in
  start)
    start_mykeystore
    exit $?
    ;;
  stop)
    stop_mykeystore
    ;;
  restart)
    stop_mykeystore
    if [ ! -z $? ]
      then
        exit $?
    fi
    start_mykeystore
    ;;
  force-reload)
    stop_mykeystore
    if [ ! -z $? ]
      then
        exit $?
    fi
    start_mykeystore
    ;;
  status)
    status_of_proc $BIN $NAME
    ;;
  *)
    echo "Usage: $NAME {start|stop|restart|status}" >&2
    exit 3
    ;;
esac

